-- MySQL Script generated by MySQL Workbench
-- Tue Mar 20 02:19:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

SET @kacscjs_init_admin_kaid = "kaid_1063314115048600759228780"; /* <- YOUR KAID HERE */

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kacscjs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kacscjs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kacscjs` DEFAULT CHARACTER SET utf8 ;
USE `kacscjs` ;

-- -----------------------------------------------------
-- Table `kacscjs`.`brackets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kacscjs`.`brackets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `contest_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kacscjs`.`contests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kacscjs`.`contests` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `program_id` BIGINT(20) NOT NULL,
  `end_date` BIGINT(20) UNSIGNED NOT NULL,
  `date_created` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  UNIQUE INDEX `program_id` (`program_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kacscjs`.`crit_entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kacscjs`.`crit_entry` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `criterion_id` INT(11) NOT NULL,
  `score` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `date_cast` BIGINT(20) UNSIGNED NOT NULL,
  `entry_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kacscjs`.`criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kacscjs`.`criteria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contest_id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `weight` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kacscjs`.`entries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kacscjs`.`entries` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `program_id` BIGINT(20) NOT NULL,
  `contest_id` INT(11) NOT NULL,
  `bracket_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `program_id` (`program_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kacscjs`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kacscjs`.`feedback` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `entry_id` INT(11) NOT NULL,
  `comment` VARCHAR(5000) NOT NULL,
  `date_written` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kacscjs`.`judges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kacscjs`.`judges` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `contest_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kacscjs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kacscjs`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `kaid` VARCHAR(255) NOT NULL,
  `level` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `kacscjsid` (`id` ASC),
  UNIQUE INDEX `kaid` (`kaid` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;

INSERT INTO users (kaid, level, name) VALUES (@kacscjs_init_admin_kaid, 2, "");

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
